language: node_js
node_js:
- 10
services:
- docker
env:
  global:
  - REACT_APP_API_BASE_URL=http://localhost:8080
  - PACT_BROKER_BASE_URL=https://jjsalamon.pact.dius.com.au
  # PACT_BROKER_TOKEN is encrypted below
  - secure: "iGBikfHuuEThMBXZg2xqAd3RXwqKhL3HFmjoY9DcHQSd2M93lLQaNJDuWbGODoh6bDsAJTXdtnTrqQXCt05qrVn+NRpkLeimdEB8yXWFZW2iFoD8UvWjrJCOI7uNpEcAYGNdegX+zR+ode9PtsIQKekBMgfxC7UVknrKb1eRXzo6jHuk5IROpK+l56tmp/XxojvXIEiM2gCCv5E3CfAQf+DW8bjjICoV6jLzS1aWOVEDTDERhKeJnn5TsY/N9f83YQqluOZ/XNSfZCJ0SDST9x6rNfVYB3sJlgYf8SH7CCO5ELZwYir/0Zvv234JAxbH/CppHzTCHzbkdWoSLU6DHtqPssRZmOFzbIG5sNQzYY/LmYc3zY0FZeNSamQGf5iZBd9WwFbHmlaKl3cSAns0VE9oics8WGI5Z89pnd+u2X3Dh3ASHKxCAYrMVBoQx6PAz/7q6WtUpXtXjExPLg6v2Q/mwxVrv/26WWu0YdJRJPf97bLDwP9ojiavDdJEtppQ5hiErz6OGjljqk6Dv/CPPybmQ94JdgcjB5uBDAESowQKXSSbYYmOqV+wH7yP0A02FfgzHLQ/9Lm3vaA/uSlM8/a+dh71qIs+HJAEG9NnQatCGXFPkexl6A1NCzGjEbPWDrl/ECAgFRUD+3JGjLr07oy6Xq/3O6hqrBh7uVukPNI="

before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
- make ci
