language: node_js
node_js:
- 10
services:
- docker
env:
  global:
  - REACT_APP_API_BASE_URL=http://localhost:8080
  - PACT_BROKER_BASE_URL=https://jjsalamon.pact.dius.com.au
  # PACT_BROKER_TOKEN is encrypted below
  - secure: "TIZat2es/WkC2f4GwEbst0lkjvsfMakX2i6QaAwW4HPnBGoy+p0SvKyCVAyvt+PYMrBnpnES2+2UU7U2U5Dc0qQY2q2mB/8HpBYpWRKt//oT7ZCs9BN0ZYFc1BQlASNF9JgfUaEg/KYtFDAMtZWTXAOpBNQWDZAvpGnoYvzh6UQnpEoKakpTt1da3gb4xWrbwu81qsDoow3D6/6qoGGzTXAzr5xn5dzV7CYRsaKQ8w90+Qz2wrUaBWt3i7lzxzSY4n/IU5HtPGbHoiYhz9VwFiUnS87+OVPRBoPt6EHXraF8np6OuKQs6comh3tu/SG0pHPRdY2zwxpgiL3vQ9QwChrZ3cUlcDYBwn7GOcChEwBJkQ2UXTDTMFjMH7ND/Z2Bhf18BctQHJjJFMeHuLdhw2K+Jw8E7pMkpf1mETyO+gZZBTzAeHR1QdiRuBuyLn+2UqqiF/mWKfypfK2H926+skzd2xYFCvORQUc/CitLcnZiLugmvGRXclYH1++DDcFRYNUi94r08FtfO7fhFY/bAN3Hv9x6B8rO6rxlq0ghYE8o2kBCDW6+okHE+QG3MTaaNXp2a+vBfj0pBKCDkkTKIqqq0bgVznY/E1wTgGQ3okAEc2/+P4bfI9Kqq6cNgsBbRTKVz0Ub8DPpczdyGpFKc1B/JBosVB8a4bOTmwuwKgI="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
- make ci
